### PR TITLE
Add RbxMouse

### PR DESCRIPTION
**Pull request by EmeraldSlash**

### CODE REVIEW

**Comment by howmanysmall** [comment]
Add it.

**Comment by EmeraldSlash** [comment]
Quick question, though - what's the correct way to organise multiple scripts in a repository? RbxMouse is supposed to be a ModuleScript with other ModuleScript children, but I'm wondering if that would work properly. I can update that if needed.

**Comment by Validark** [comment]
What functionality does this library add?

**Comment by EmeraldSlash** [comment]
Consolidates mouse-related things into one main library and adds features
people may want. It really only adds some signals (MouseButton3Click as the
most extreme example), adds some extra customisation, and merges in a
couple of things from UIS (mouse icon enabled).

**Comment by Validark** [comment]
Still waiting on this https://github.com/EmeraldSlash/RbxMouse/pull/7

**Comment by EmeraldSlash** [comment]
Sorry about that, I've been mostly off Roblox recently so haven't been checking GitHub either.

**Comment by Validark** [comment]
I misread the activity on this timeline which occurred after I asked you to merge the PR. I thought you merged it when in fact you did not, so RoStrap will not install this library properly. Thus, I have temporarily removed it from RoStrap.

**Pull request merged**
